name: Flutter Nightly Build

on:
  workflow_dispatch:

permissions: write-all
  
jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
